import type { Transaction } from "../interfaces/Types";

export const mockTransactions: Transaction[] = [
  {
    "id": "tx_100000",
    "amount": 915.09,
    "currency": "USD",
    "status": "completed",
    "date": "2024-07-23T00:00:00Z",
    "description": "Groceries",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Riley Brown",
      "email": "riley.brown0@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "2321",
    "fees": 23.17,
  },
  {
    "id": "tx_100001",
    "amount": 1544.91,
    "currency": "USD",
    "status": "completed",
    "date": "2024-08-05T00:00:00Z",
    "description": "Electronics",
    "merchant": "Tech Store",
    "customer": {
      "name": "Alex Williams",
      "email": "alex.williams1@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "6543",
    "fees": 35.53,
    "formattedAmount": "",
    "formattedFees": "",
  },
  {
    "id": "tx_100002",
    "amount": 594.12,
    "currency": "USD",
    "status": "failed",
    "date": "2024-10-20T00:00:00Z",
    "description": "Groceries",
    "merchant": "City Power",
    "customer": {
      "name": "Reese Miller",
      "email": "reese.miller2@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "3134",
    "fees": 8.19,
  },
  {
    "id": "tx_100003",
    "amount": 1260.86,
    "currency": "USD",
    "status": "failed",
    "date": "2024-08-10T00:00:00Z",
    "description": "Online purchase",
    "merchant": "QuickEats",
    "customer": {
      "name": "Drew Miller",
      "email": "drew.miller3@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "9326",
    "fees": 22.73,


  },
  {
    "id": "tx_100004",
    "amount": 204.63,
    "currency": "USD",
    "status": "pending",
    "date": "2024-04-27T00:00:00Z",
    "description": "Groceries",
    "merchant": "QuickEats",
    "customer": {
      "name": "Jordan Wilson",
      "email": "jordan.wilson4@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "4020",
    "fees": 2.38,
  },
  {
    "id": "tx_100005",
    "amount": 207.69,
    "currency": "USD",
    "status": "completed",
    "date": "2024-03-02T00:00:00Z",
    "description": "Dinner",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Casey Davis",
      "email": "casey.davis5@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "6771",
    "fees": 4.83,
  },
  {
    "id": "tx_100006",
    "amount": 268.65,
    "currency": "USD",
    "status": "failed",
    "date": "2024-12-15T00:00:00Z",
    "description": "Subscription",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Reese Smith",
      "email": "reese.smith6@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7270",
    "fees": 7.55,
  },
  {
    "id": "tx_100007",
    "amount": 1292.98,
    "currency": "USD",
    "status": "failed",
    "date": "2024-04-22T00:00:00Z",
    "description": "Online purchase",
    "merchant": "City Power",
    "customer": {
      "name": "Alex Johnson",
      "email": "alex.johnson7@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "8615",
    "fees": 27.07,
  },
  {
    "id": "tx_100008",
    "amount": 1656.31,
    "currency": "USD",
    "status": "completed",
    "date": "2024-11-29T00:00:00Z",
    "description": "Electronics",
    "merchant": "QuickEats",
    "customer": {
      "name": "Reese Wilson",
      "email": "reese.wilson8@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "2746",
    "fees": 22.52,
  },
  {
    "id": "tx_100009",
    "amount": 1692.1,
    "currency": "USD",
    "status": "pending",
    "date": "2024-02-24T00:00:00Z",
    "description": "Utility bill",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Chris Jones",
      "email": "chris.jones9@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "1846",
    "fees": 20.14,
  },
  {
    "id": "tx_100010",
    "amount": 194.85,
    "currency": "USD",
    "status": "failed",
    "date": "2024-01-29T00:00:00Z",
    "description": "Groceries",
    "merchant": "Tech Store",
    "customer": {
      "name": "Jordan Rodriguez",
      "email": "jordan.rodriguez10@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "2971",
    "fees": 3.8,
  },
  {
    "id": "tx_100011",
    "amount": 107.27,
    "currency": "USD",
    "status": "failed",
    "date": "2024-04-21T00:00:00Z",
    "description": "Groceries",
    "merchant": "QuickEats",
    "customer": {
      "name": "Jamie Williams",
      "email": "jamie.williams11@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "1523",
    "fees": 1.15,
  },
  {
    "id": "tx_100012",
    "amount": 1177.76,
    "currency": "USD",
    "status": "pending",
    "date": "2024-11-07T00:00:00Z",
    "description": "Groceries",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Jamie Garcia",
      "email": "jamie.garcia12@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "4915",
    "fees": 25.24,
  },
  {
    "id": "tx_100013",
    "amount": 1633.5,
    "currency": "USD",
    "status": "failed",
    "date": "2024-04-01T00:00:00Z",
    "description": "Online purchase",
    "merchant": "Tech Store",
    "customer": {
      "name": "Alex Jones",
      "email": "alex.jones13@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1269",
    "fees": 45.18,
  },
  {
    "id": "tx_100014",
    "amount": 255.04,
    "currency": "USD",
    "status": "pending",
    "date": "2024-11-06T00:00:00Z",
    "description": "Subscription",
    "merchant": "QuickEats",
    "customer": {
      "name": "Jamie Williams",
      "email": "jamie.williams14@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "4251",
    "fees": 4.06,
  },
  {
    "id": "tx_100015",
    "amount": 338.58,
    "currency": "USD",
    "status": "failed",
    "date": "2024-08-16T00:00:00Z",
    "description": "Dinner",
    "merchant": "City Power",
    "customer": {
      "name": "Chris Miller",
      "email": "chris.miller15@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "4429",
    "fees": 3.54,
  },
  {
    "id": "tx_100016",
    "amount": 522.42,
    "currency": "USD",
    "status": "completed",
    "date": "2024-08-29T00:00:00Z",
    "description": "Subscription",
    "merchant": "Tech Store",
    "customer": {
      "name": "Morgan Wilson",
      "email": "morgan.wilson16@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "6550",
    "fees": 14.75,
  },
  {
    "id": "tx_100017",
    "amount": 754.93,
    "currency": "USD",
    "status": "completed",
    "date": "2024-04-19T00:00:00Z",
    "description": "Dinner",
    "merchant": "BookWorld",
    "customer": {
      "name": "Riley Davis",
      "email": "riley.davis17@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "5591",
    "fees": 17.46,
  },
  {
    "id": "tx_100018",
    "amount": 1611.86,
    "currency": "USD",
    "status": "failed",
    "date": "2024-05-07T00:00:00Z",
    "description": "Groceries",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Casey Wilson",
      "email": "casey.wilson18@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "7311",
    "fees": 43.04,
  },
  {
    "id": "tx_100019",
    "amount": 1928.12,
    "currency": "USD",
    "status": "failed",
    "date": "2024-10-11T00:00:00Z",
    "description": "Online purchase",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Jordan Davis",
      "email": "jordan.davis19@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "8806",
    "fees": 50.34,
  },
  {
    "id": "tx_100020",
    "amount": 1071.64,
    "currency": "USD",
    "status": "failed",
    "date": "2024-06-10T00:00:00Z",
    "description": "Utility bill",
    "merchant": "QuickEats",
    "customer": {
      "name": "Reese Miller",
      "email": "reese.miller20@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7609",
    "fees": 31.81,
  },
  {
    "id": "tx_100021",
    "amount": 1613.62,
    "currency": "USD",
    "status": "failed",
    "date": "2024-02-22T00:00:00Z",
    "description": "Utility bill",
    "merchant": "Tech Store",
    "customer": {
      "name": "Morgan Brown",
      "email": "morgan.brown21@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "9419",
    "fees": 38.74,
  },
  {
    "id": "tx_100022",
    "amount": 959.13,
    "currency": "USD",
    "status": "completed",
    "date": "2024-03-06T00:00:00Z",
    "description": "Online purchase",
    "merchant": "City Power",
    "customer": {
      "name": "Riley Rodriguez",
      "email": "riley.rodriguez22@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1643",
    "fees": 27.14,
  },
  {
    "id": "tx_100023",
    "amount": 1156.51,
    "currency": "USD",
    "status": "pending",
    "date": "2024-03-06T00:00:00Z",
    "description": "Dinner",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Drew Miller",
      "email": "drew.miller23@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "6386",
    "fees": 19.08,
  },
  {
    "id": "tx_100024",
    "amount": 605.97,
    "currency": "USD",
    "status": "pending",
    "date": "2025-01-09T00:00:00Z",
    "description": "Dinner",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Jordan Johnson",
      "email": "jordan.johnson24@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7333",
    "fees": 8.84,
  },
  {
    "id": "tx_100025",
    "amount": 840.58,
    "currency": "USD",
    "status": "completed",
    "date": "2024-01-24T00:00:00Z",
    "description": "Utility bill",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Riley Garcia",
      "email": "riley.garcia25@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "5705",
    "fees": 11.84,
  },
  {
    "id": "tx_100026",
    "amount": 1172.07,
    "currency": "USD",
    "status": "pending",
    "date": "2024-06-01T00:00:00Z",
    "description": "Dinner",
    "merchant": "BookWorld",
    "customer": {
      "name": "Taylor Brown",
      "email": "taylor.brown26@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "5146",
    "fees": 22.27,
  },
  {
    "id": "tx_100027",
    "amount": 821.7,
    "currency": "USD",
    "status": "completed",
    "date": "2024-07-24T00:00:00Z",
    "description": "Online purchase",
    "merchant": "City Power",
    "customer": {
      "name": "Alex Smith",
      "email": "alex.smith27@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "5241",
    "fees": 11.43,
  },
  {
    "id": "tx_100028",
    "amount": 1086.34,
    "currency": "USD",
    "status": "failed",
    "date": "2024-06-17T00:00:00Z",
    "description": "Electronics",
    "merchant": "City Power",
    "customer": {
      "name": "Riley Smith",
      "email": "riley.smith28@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "8154",
    "fees": 24.6,
  },
  {
    "id": "tx_100029",
    "amount": 1801.19,
    "currency": "USD",
    "status": "failed",
    "date": "2024-08-04T00:00:00Z",
    "description": "Online purchase",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Alex Smith",
      "email": "alex.smith29@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "4352",
    "fees": 51.37,
  },
  {
    "id": "tx_100030",
    "amount": 357.53,
    "currency": "USD",
    "status": "failed",
    "date": "2024-03-26T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Jamie Wilson",
      "email": "jamie.wilson30@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "9656",
    "fees": 4.81,
  },
  {
    "id": "tx_100031",
    "amount": 461.2,
    "currency": "USD",
    "status": "pending",
    "date": "2024-12-12T00:00:00Z",
    "description": "Electronics",
    "merchant": "City Power",
    "customer": {
      "name": "Alex Wilson",
      "email": "alex.wilson31@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1689",
    "fees": 4.71,
  },
  {
    "id": "tx_100032",
    "amount": 291.02,
    "currency": "USD",
    "status": "completed",
    "date": "2024-01-31T00:00:00Z",
    "description": "Electronics",
    "merchant": "City Power",
    "customer": {
      "name": "Jordan Wilson",
      "email": "jordan.wilson32@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1737",
    "fees": 6.55,
  },
  {
    "id": "tx_100033",
    "amount": 495.86,
    "currency": "USD",
    "status": "pending",
    "date": "2024-12-02T00:00:00Z",
    "description": "Utility bill",
    "merchant": "City Power",
    "customer": {
      "name": "Riley Garcia",
      "email": "riley.garcia33@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "6206",
    "fees": 9.17,
  },
  {
    "id": "tx_100034",
    "amount": 352.51,
    "currency": "USD",
    "status": "completed",
    "date": "2024-02-02T00:00:00Z",
    "description": "Utility bill",
    "merchant": "City Power",
    "customer": {
      "name": "Drew Garcia",
      "email": "drew.garcia34@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "7698",
    "fees": 5.27,


  },
  {
    "id": "tx_100035",
    "amount": 1419.74,
    "currency": "USD",
    "status": "pending",
    "date": "2024-07-05T00:00:00Z",
    "description": "Electronics",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Taylor Williams",
      "email": "taylor.williams35@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "7272",
    "fees": 17.76,
  },
  {
    "id": "tx_100036",
    "amount": 799.15,
    "currency": "USD",
    "status": "completed",
    "date": "2024-10-24T00:00:00Z",
    "description": "Utility bill",
    "merchant": "Tech Store",
    "customer": {
      "name": "Drew Williams",
      "email": "drew.williams36@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7310",
    "fees": 10.55,
  },
  {
    "id": "tx_100037",
    "amount": 921.85,
    "currency": "USD",
    "status": "completed",
    "date": "2024-11-26T00:00:00Z",
    "description": "Utility bill",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Taylor Johnson",
      "email": "taylor.johnson37@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "7933",
    "fees": 17.17,
  },
  {
    "id": "tx_100038",
    "amount": 791.42,
    "currency": "USD",
    "status": "failed",
    "date": "2024-08-14T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Tech Store",
    "customer": {
      "name": "Morgan Jones",
      "email": "morgan.jones38@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "2382",
    "fees": 21.22,
  },
  {
    "id": "tx_100039",
    "amount": 849.55,
    "currency": "USD",
    "status": "completed",
    "date": "2024-03-12T00:00:00Z",
    "description": "Subscription",
    "merchant": "QuickEats",
    "customer": {
      "name": "Casey Miller",
      "email": "casey.miller39@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1341",
    "fees": 24.21,
  },
  {
    "id": "tx_100040",
    "amount": 139.64,
    "currency": "USD",
    "status": "failed",
    "date": "2024-06-29T00:00:00Z",
    "description": "Subscription",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Morgan Smith",
      "email": "morgan.smith40@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "9609",
    "fees": 3.74,
  },
  {
    "id": "tx_100041",
    "amount": 1867.74,
    "currency": "USD",
    "status": "pending",
    "date": "2024-03-14T00:00:00Z",
    "description": "Utility bill",
    "merchant": "QuickEats",
    "customer": {
      "name": "Taylor Williams",
      "email": "taylor.williams41@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "2422",
    "fees": 45.18,
  },
  {
    "id": "tx_100042",
    "amount": 921.32,
    "currency": "USD",
    "status": "pending",
    "date": "2024-08-11T00:00:00Z",
    "description": "Electronics",
    "merchant": "BookWorld",
    "customer": {
      "name": "Taylor Williams",
      "email": "taylor.williams42@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "1410",
    "fees": 17.9,
  },
  {
    "id": "tx_100043",
    "amount": 1461.48,
    "currency": "USD",
    "status": "failed",
    "date": "2024-12-03T00:00:00Z",
    "description": "Dinner",
    "merchant": "BookWorld",
    "customer": {
      "name": "Jamie Johnson",
      "email": "jamie.johnson43@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7676",
    "fees": 42.08,
  },
  {
    "id": "tx_100044",
    "amount": 29.47,
    "currency": "USD",
    "status": "completed",
    "date": "2024-02-22T00:00:00Z",
    "description": "Utility bill",
    "merchant": "Tech Store",
    "customer": {
      "name": "Alex Rodriguez",
      "email": "alex.rodriguez44@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "6543",
    "fees": 0.66,
  },
  {
    "id": "tx_100045",
    "amount": 1671.53,
    "currency": "USD",
    "status": "pending",
    "date": "2024-07-24T00:00:00Z",
    "description": "Groceries",
    "merchant": "Tech Store",
    "customer": {
      "name": "Drew Williams",
      "email": "drew.williams45@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7950",
    "fees": 27.94,
  },
  {
    "id": "tx_100046",
    "amount": 1881.95,
    "currency": "USD",
    "status": "completed",
    "date": "2024-11-29T00:00:00Z",
    "description": "Electronics",
    "merchant": "Tech Store",
    "customer": {
      "name": "Alex Rodriguez",
      "email": "alex.rodriguez46@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "9949",
    "fees": 22.05,
  },
  {
    "id": "tx_100047",
    "amount": 377.44,
    "currency": "USD",
    "status": "pending",
    "date": "2024-05-02T00:00:00Z",
    "description": "Subscription",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Chris Smith",
      "email": "chris.smith47@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "5561",
    "fees": 6.97,
  },
  {
    "id": "tx_100048",
    "amount": 1330.4,
    "currency": "USD",
    "status": "failed",
    "date": "2024-10-08T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Jamie Rodriguez",
      "email": "jamie.rodriguez48@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "6167",
    "fees": 39.06,
  },
  {
    "id": "tx_100049",
    "amount": 1079.17,
    "currency": "USD",
    "status": "completed",
    "date": "2025-01-06T00:00:00Z",
    "description": "Dinner",
    "merchant": "Tech Store",
    "customer": {
      "name": "Chris Brown",
      "email": "chris.brown49@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "2399",
    "fees": 31.5,
  },
  {
    "id": "tx_100050",
    "amount": 422.95,
    "currency": "USD",
    "status": "pending",
    "date": "2024-06-27T00:00:00Z",
    "description": "Dinner",
    "merchant": "City Power",
    "customer": {
      "name": "Riley Jones",
      "email": "riley.jones50@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "1051",
    "fees": 10.94,
  },
  {
    "id": "tx_100051",
    "amount": 167.45,
    "currency": "USD",
    "status": "pending",
    "date": "2024-08-05T00:00:00Z",
    "description": "Dinner",
    "merchant": "QuickEats",
    "customer": {
      "name": "Morgan Rodriguez",
      "email": "morgan.rodriguez51@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "2429",
    "fees": 4.5,
  },
  {
    "id": "tx_100052",
    "amount": 1300.88,
    "currency": "USD",
    "status": "completed",
    "date": "2024-03-13T00:00:00Z",
    "description": "Online purchase",
    "merchant": "Tech Store",
    "customer": {
      "name": "Jamie Williams",
      "email": "jamie.williams52@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "2001",
    "fees": 27.68,
  },
  {
    "id": "tx_100053",
    "amount": 25.3,
    "currency": "USD",
    "status": "completed",
    "date": "2024-04-27T00:00:00Z",
    "description": "Subscription",
    "merchant": "BookWorld",
    "customer": {
      "name": "Chris Davis",
      "email": "chris.davis53@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "1323",
    "fees": 0.48,
  },
  {
    "id": "tx_100054",
    "amount": 409.0,
    "currency": "USD",
    "status": "failed",
    "date": "2024-04-04T00:00:00Z",
    "description": "Dinner",
    "merchant": "Tech Store",
    "customer": {
      "name": "Riley Johnson",
      "email": "riley.johnson54@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7742",
    "fees": 5.33,
  },
  {
    "id": "tx_100055",
    "amount": 1367.15,
    "currency": "USD",
    "status": "completed",
    "date": "2024-09-30T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Jamie Garcia",
      "email": "jamie.garcia55@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1422",
    "fees": 32.75,
  },
  {
    "id": "tx_100056",
    "amount": 276.99,
    "currency": "USD",
    "status": "completed",
    "date": "2024-05-03T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Chris Brown",
      "email": "chris.brown56@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "6414",
    "fees": 5.78,
  },
  {
    "id": "tx_100057",
    "amount": 352.53,
    "currency": "USD",
    "status": "failed",
    "date": "2024-06-03T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Jordan Miller",
      "email": "jordan.miller57@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "1731",
    "fees": 8.13,
  },
  {
    "id": "tx_100058",
    "amount": 920.92,
    "currency": "USD",
    "status": "failed",
    "date": "2024-09-14T00:00:00Z",
    "description": "Electronics",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Jordan Rodriguez",
      "email": "jordan.rodriguez58@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "3740",
    "fees": 21.74,
  },
  {
    "id": "tx_100059",
    "amount": 1537.87,
    "currency": "USD",
    "status": "failed",
    "date": "2024-06-21T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Drew Smith",
      "email": "drew.smith59@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "7386",
    "fees": 22.64,
  },
  {
    "id": "tx_100060",
    "amount": 594.8,
    "currency": "USD",
    "status": "completed",
    "date": "2024-11-05T00:00:00Z",
    "description": "Online purchase",
    "merchant": "QuickEats",
    "customer": {
      "name": "Jamie Johnson",
      "email": "jamie.johnson60@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "4874",
    "fees": 14.27,
  },
  {
    "id": "tx_100061",
    "amount": 182.85,
    "currency": "USD",
    "status": "failed",
    "date": "2024-08-08T00:00:00Z",
    "description": "Groceries",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Chris Rodriguez",
      "email": "chris.rodriguez61@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "5087",
    "fees": 2.06,
  },
  {
    "id": "tx_100062",
    "amount": 1232.85,
    "currency": "USD",
    "status": "completed",
    "date": "2024-11-05T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "QuickEats",
    "customer": {
      "name": "Chris Johnson",
      "email": "chris.johnson62@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "7112",
    "fees": 26.56,
  },
  {
    "id": "tx_100063",
    "amount": 1565.98,
    "currency": "USD",
    "status": "pending",
    "date": "2024-02-13T00:00:00Z",
    "description": "Dinner",
    "merchant": "City Power",
    "customer": {
      "name": "Morgan Smith",
      "email": "morgan.smith63@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "3434",
    "fees": 24.58,
  },
  {
    "id": "tx_100064",
    "amount": 635.25,
    "currency": "USD",
    "status": "pending",
    "date": "2024-03-17T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Reese Brown",
      "email": "reese.brown64@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "9144",
    "fees": 8.28,
  },
  {
    "id": "tx_100065",
    "amount": 1650.73,
    "currency": "USD",
    "status": "completed",
    "date": "2024-11-13T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "BookWorld",
    "customer": {
      "name": "Riley Smith",
      "email": "riley.smith65@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "6058",
    "fees": 30.74,
  },
  {
    "id": "tx_100066",
    "amount": 1902.49,
    "currency": "USD",
    "status": "completed",
    "date": "2024-02-26T00:00:00Z",
    "description": "Utility bill",
    "merchant": "BookWorld",
    "customer": {
      "name": "Jordan Rodriguez",
      "email": "jordan.rodriguez66@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "8060",
    "fees": 28.72,
  },
  {
    "id": "tx_100067",
    "amount": 1169.54,
    "currency": "USD",
    "status": "pending",
    "date": "2024-06-30T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Chris Wilson",
      "email": "chris.wilson67@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "4765",
    "fees": 23.82,
  },
  {
    "id": "tx_100068",
    "amount": 88.23,
    "currency": "USD",
    "status": "completed",
    "date": "2024-07-23T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "City Power",
    "customer": {
      "name": "Alex Rodriguez",
      "email": "alex.rodriguez68@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "4002",
    "fees": 1.65,
  },
  {
    "id": "tx_100069",
    "amount": 1346.58,
    "currency": "USD",
    "status": "failed",
    "date": "2024-11-03T00:00:00Z",
    "description": "Utility bill",
    "merchant": "BookWorld",
    "customer": {
      "name": "Riley Johnson",
      "email": "riley.johnson69@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1136",
    "fees": 29.57,
  },
  {
    "id": "tx_100070",
    "amount": 751.35,
    "currency": "USD",
    "status": "failed",
    "date": "2024-03-12T00:00:00Z",
    "description": "Dinner",
    "merchant": "BookWorld",
    "customer": {
      "name": "Casey Williams",
      "email": "casey.williams70@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "8350",
    "fees": 11.17,
  },
  {
    "id": "tx_100071",
    "amount": 787.47,
    "currency": "USD",
    "status": "failed",
    "date": "2024-07-20T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "QuickEats",
    "customer": {
      "name": "Jordan Williams",
      "email": "jordan.williams71@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "4564",
    "fees": 20.72,
  },
  {
    "id": "tx_100072",
    "amount": 828.71,
    "currency": "USD",
    "status": "completed",
    "date": "2024-05-24T00:00:00Z",
    "description": "Electronics",
    "merchant": "BookWorld",
    "customer": {
      "name": "Riley Miller",
      "email": "riley.miller72@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "6957",
    "fees": 8.87,
  },
  {
    "id": "tx_100073",
    "amount": 1588.36,
    "currency": "USD",
    "status": "pending",
    "date": "2024-07-09T00:00:00Z",
    "description": "Dinner",
    "merchant": "BookWorld",
    "customer": {
      "name": "Alex Rodriguez",
      "email": "alex.rodriguez73@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "4345",
    "fees": 41.01,
  },
  {
    "id": "tx_100074",
    "amount": 1383.36,
    "currency": "USD",
    "status": "pending",
    "date": "2024-03-23T00:00:00Z",
    "description": "Dinner",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Reese Smith",
      "email": "reese.smith74@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "6949",
    "fees": 33.15,
  },
  {
    "id": "tx_100075",
    "amount": 485.35,
    "currency": "USD",
    "status": "completed",
    "date": "2024-09-04T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Morgan Rodriguez",
      "email": "morgan.rodriguez75@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "6080",
    "fees": 6.36,
  },
  {
    "id": "tx_100076",
    "amount": 819.18,
    "currency": "USD",
    "status": "completed",
    "date": "2024-03-11T00:00:00Z",
    "description": "Subscription",
    "merchant": "QuickEats",
    "customer": {
      "name": "Chris Rodriguez",
      "email": "chris.rodriguez76@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "9310",
    "fees": 13.37,
  },
  {
    "id": "tx_100077",
    "amount": 63.55,
    "currency": "USD",
    "status": "pending",
    "date": "2024-05-21T00:00:00Z",
    "description": "Electronics",
    "merchant": "BookWorld",
    "customer": {
      "name": "Taylor Brown",
      "email": "taylor.brown77@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "6648",
    "fees": 0.89,
  },
  {
    "id": "tx_100078",
    "amount": 386.09,
    "currency": "USD",
    "status": "completed",
    "date": "2024-05-15T00:00:00Z",
    "description": "Dinner",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Morgan Williams",
      "email": "morgan.williams78@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "2537",
    "fees": 4.23,
  },
  {
    "id": "tx_100079",
    "amount": 443.48,
    "currency": "USD",
    "status": "pending",
    "date": "2024-05-11T00:00:00Z",
    "description": "Electronics",
    "merchant": "Tech Store",
    "customer": {
      "name": "Riley Jones",
      "email": "riley.jones79@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "5185",
    "fees": 5.04,
  },
  {
    "id": "tx_100080",
    "amount": 1991.93,
    "currency": "USD",
    "status": "failed",
    "date": "2024-03-16T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "City Power",
    "customer": {
      "name": "Reese Wilson",
      "email": "reese.wilson80@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "2609",
    "fees": 44.94,
  },
  {
    "id": "tx_100081",
    "amount": 815.05,
    "currency": "USD",
    "status": "failed",
    "date": "2024-10-24T00:00:00Z",
    "description": "Groceries",
    "merchant": "Tech Store",
    "customer": {
      "name": "Reese Williams",
      "email": "reese.williams81@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "5208",
    "fees": 21.11,
  },
  {
    "id": "tx_100082",
    "amount": 364.5,
    "currency": "USD",
    "status": "completed",
    "date": "2024-11-06T00:00:00Z",
    "description": "Utility bill",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Taylor Garcia",
      "email": "taylor.garcia82@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "4785",
    "fees": 9.0,
  },
  {
    "id": "tx_100083",
    "amount": 763.14,
    "currency": "USD",
    "status": "pending",
    "date": "2024-10-26T00:00:00Z",
    "description": "Groceries",
    "merchant": "City Power",
    "customer": {
      "name": "Reese Jones",
      "email": "reese.jones83@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "2668",
    "fees": 17.38,
  },
  {
    "id": "tx_100084",
    "amount": 992.69,
    "currency": "USD",
    "status": "completed",
    "date": "2024-02-20T00:00:00Z",
    "description": "Electronics",
    "merchant": "Tech Store",
    "customer": {
      "name": "Drew Smith",
      "email": "drew.smith84@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "8782",
    "fees": 28.62,
  },
  {
    "id": "tx_100085",
    "amount": 1300.56,
    "currency": "USD",
    "status": "failed",
    "date": "2024-08-27T00:00:00Z",
    "description": "Utility bill",
    "merchant": "BookWorld",
    "customer": {
      "name": "Riley Rodriguez",
      "email": "riley.rodriguez85@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1428",
    "fees": 33.25,
  },
  {
    "id": "tx_100086",
    "amount": 1604.77,
    "currency": "USD",
    "status": "failed",
    "date": "2024-04-28T00:00:00Z",
    "description": "Online purchase",
    "merchant": "QuickEats",
    "customer": {
      "name": "Alex Smith",
      "email": "alex.smith86@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "8817",
    "fees": 32.65,
  },
  {
    "id": "tx_100087",
    "amount": 1876.46,
    "currency": "USD",
    "status": "failed",
    "date": "2024-08-09T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "BookWorld",
    "customer": {
      "name": "Drew Johnson",
      "email": "drew.johnson87@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "8102",
    "fees": 24.31,
  },
  {
    "id": "tx_100088",
    "amount": 709.88,
    "currency": "USD",
    "status": "pending",
    "date": "2025-01-12T00:00:00Z",
    "description": "Groceries",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Drew Miller",
      "email": "drew.miller88@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "4342",
    "fees": 10.38,
  },
  {
    "id": "tx_100089",
    "amount": 324.5,
    "currency": "USD",
    "status": "pending",
    "date": "2024-12-29T00:00:00Z",
    "description": "Groceries",
    "merchant": "Tech Store",
    "customer": {
      "name": "Jordan Wilson",
      "email": "jordan.wilson89@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "4368",
    "fees": 7.37,
  },
  {
    "id": "tx_100090",
    "amount": 785.5,
    "currency": "USD",
    "status": "pending",
    "date": "2024-03-07T00:00:00Z",
    "description": "Groceries",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Taylor Miller",
      "email": "taylor.miller90@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "1661",
    "fees": 7.87,
  },
  {
    "id": "tx_100091",
    "amount": 1324.63,
    "currency": "USD",
    "status": "pending",
    "date": "2024-03-14T00:00:00Z",
    "description": "Flight tickets",
    "merchant": "Tech Store",
    "customer": {
      "name": "Riley Smith",
      "email": "riley.smith91@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "5517",
    "fees": 36.53,
  },
  {
    "id": "tx_100092",
    "amount": 556.99,
    "currency": "USD",
    "status": "failed",
    "date": "2024-06-03T00:00:00Z",
    "description": "Utility bill",
    "merchant": "QuickEats",
    "customer": {
      "name": "Casey Rodriguez",
      "email": "casey.rodriguez92@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "6552",
    "fees": 13.5,
  },
  {
    "id": "tx_100093",
    "amount": 413.42,
    "currency": "USD",
    "status": "pending",
    "date": "2024-06-30T00:00:00Z",
    "description": "Online purchase",
    "merchant": "Tech Store",
    "customer": {
      "name": "Jordan Jones",
      "email": "jordan.jones93@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "4407",
    "fees": 12.24,
  },
  {
    "id": "tx_100094",
    "amount": 1156.39,
    "currency": "USD",
    "status": "completed",
    "date": "2024-07-27T00:00:00Z",
    "description": "Dinner",
    "merchant": "SaaS Platform",
    "customer": {
      "name": "Chris Rodriguez",
      "email": "chris.rodriguez94@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "4073",
    "fees": 28.56,
  },
  {
    "id": "tx_100095",
    "amount": 390.39,
    "currency": "USD",
    "status": "failed",
    "date": "2024-10-23T00:00:00Z",
    "description": "Subscription",
    "merchant": "Tech Store",
    "customer": {
      "name": "Morgan Brown",
      "email": "morgan.brown95@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "4765",
    "fees": 7.85,
  },
  {
    "id": "tx_100096",
    "amount": 1443.99,
    "currency": "USD",
    "status": "pending",
    "date": "2024-10-09T00:00:00Z",
    "description": "Electronics",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Casey Smith",
      "email": "casey.smith96@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "5511",
    "fees": 41.34,
  },
  {
    "id": "tx_100097",
    "amount": 536.54,
    "currency": "USD",
    "status": "pending",
    "date": "2024-05-17T00:00:00Z",
    "description": "Electronics",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Drew Davis",
      "email": "drew.davis97@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "2919",
    "fees": 11.6,
  },
  {
    "id": "tx_100098",
    "amount": 881.35,
    "currency": "USD",
    "status": "completed",
    "date": "2024-12-04T00:00:00Z",
    "description": "Dinner",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Jamie Jones",
      "email": "jamie.jones98@example.com"
    },
    "paymentMethod": "debit_card",
    "cardLast4": "3785",
    "fees": 24.84,
  },
  {
    "id": "tx_100099",
    "amount": 489.83,
    "currency": "USD",
    "status": "completed",
    "date": "2024-04-13T00:00:00Z",
    "description": "Groceries",
    "merchant": "Home Comfort",
    "customer": {
      "name": "Casey Rodriguez",
      "email": "casey.rodriguez99@example.com"
    },
    "paymentMethod": "credit_card",
    "cardLast4": "2452",
    "fees": 11.04,
  },
  {
    "id": "tx_100100",
    "amount": 1835.9,
    "currency": "USD",
    "status": "pending",
    "date": "2025-01-01T00:00:00Z",
    "description": "Groceries",
    "merchant": "Fresh Market",
    "customer": {
      "name": "Casey Davis",
      "email": "casey.davis100@example.com"
    },
    "paymentMethod": "bank_transfer",
    "cardLast4": "8521",
    "fees": 22.03,
  }
];
